spring:
  datasource:
    username: root
    password: "Oportoeumanacao1893@"
    url: jdbc:mysql://localhost:3306/rest_spring_boot_udemy?useTimezone=true&serverTimezone=UTC&useSSL=false

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework: INFO
    #    org.springframework: DEBUG
    org.springframework.security: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG
    #    org.hibernate.SQL: INFO
    #org.hibernate.type: INFO
    #    org.hibernate.type: TRACE
    pt.nomad: DEBUG
    org: INFO

---

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        batch_size: 100
        order_inserts: true
        order_updates: true
  config:
    activate:
      on-profile: initialize


